# Generated by Django 4.1.5 on 2023-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approv',
            field=models.BooleanField(default=False, verbose_name='Соглашение про отправку уведомлений на почту'),
        ),
    ]
